### ISSUE TITLE
GLM-4-Voice开源

### ISSUE THREAD

**Issue by MiChongGET** [Henry-23/VideoChat#1]
你好，GLM-4-Voice端到端语音模型已经开源了，作者有没有考虑将其集成到该项目中去呢？

**Comment by Henry-23** [comment]
目前已经集成端到端语音模型，后续会继续优化

**Comment by MiChongGET** [comment]
> 目前已经集成端到端语音模型，后续会继续优化

大佬牛啊，加鸡腿![35513246](https://github.com/user-attachments/assets/229ec331-5ece-499c-a2a5-23fcc5712619)
