### ISSUE TITLE
数字人形象视频

### ISSUE THREAD

**Issue by hyraymond1** [Henry-23/VideoChat#11]
请问数字人形象视频如何准备,什么格式?多长时间,录制好后,软件是如何使用这个形象视频的?

**Comment by Henry-23** [comment]
参考[这个说明](https://github.com/Henry-23/VideoChat?tab=readme-ov-file#51-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E5%AD%97%E4%BA%BA%E5%BD%A2%E8%B1%A1)

**Comment by Henry-23** [comment]
mp4格式即可，视频时长没有限制，基于音频对形象视频做唇形同步

**Comment by hyraymond1** [comment]
谢谢!
