### ISSUE TITLE
回答文本生成不完整，卡住

### ISSUE THREAD

**Issue by LHB-kk** [Henry-23/VideoChat#12]
你好，我在使用cascade_only分支的时候遇到回答文本流式输出卡住的问题，我看项目的打印日志，LLM API的推理服务是成功的。
![image](https://github.com/user-attachments/assets/75252551-c088-4cca-b366-3f9d6564643a)
![image](https://github.com/user-attachments/assets/45cd6827-1647-40ce-8fb1-58291caf1554)
日志打印了如下信息：
![image](https://github.com/user-attachments/assets/7026b56c-8378-48e6-b407-6f6158d80bd5)

**Comment by Henry-23** [comment]
<img width="389" alt="image" src="https://github.com/user-attachments/assets/aeaad627-eaba-492e-862d-85006d27824c">
看起来是TTS没有成功推理。如果用的Cosyvoice API的话需要在[阿里云](https://help.aliyun.com/zh/dashscope/developer-reference/cosyvoice-api-details)开通这个服务。如果不想开通的话用GPT-Sovits进行TTS的推理

**Comment by LHB-kk** [comment]
我用的Cosyvoice APi ，但是有时候不会出现卡住的问题，有时候又会出现。
![image](https://github.com/user-attachments/assets/e6231c54-456c-43c5-9ad4-fdab0c878b65)
![image](https://github.com/user-attachments/assets/d84ba276-2246-498a-ade5-3d964a7bf251)
![image](https://github.com/user-attachments/assets/8c565797-80a0-441e-8dda-88a0c6b0e569)

**Comment by LHB-kk** [comment]
> <img alt="image" width="389" src="https://private-user-images.githubusercontent.com/57001881/386918648-aeaad627-eaba-492e-862d-85006d27824c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTc4NjMsIm5iZiI6MTczMTgxNzU2MywicGF0aCI6Ii81NzAwMTg4MS8zODY5MTg2NDgtYWVhYWQ2MjctZWFiYS00OTJlLTg2MmQtODUwMDZkMjc4MjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA0MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYmM2N2I4OWYxY2JhMzMwZWI3YjE1OGQwNTcxNDg2YWI2OGFkZDU4ZmI1NTEwOWUzMmZkMTdmN2U2MDVjMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wa4NB5YOSGhqvEgUGLgaxg5FkbmIqNYihsXOsIkOJLg"> 看起来是TTS没有成功推理。如果用的Cosyvoice API的话需要在[阿里云](https://help.aliyun.com/zh/dashscope/developer-reference/cosyvoice-api-details)开通这个服务。如果不想开通的话用GPT-Sovits进行TTS的推理

后面，我改用了GPT-Sovits进行TTS推理，试了好几次，就都不会出现卡住的问题。
