### ISSUE TITLE
【死循环】

### ISSUE THREAD

**Issue by ForgetThatNight** [Henry-23/VideoChat#14]
点击提交后进入死循环，没有报错也没有打印其他信息，
`INFO:     171.88.165.224:51667 - "GET /gradio_api/stream/aovtw3pnsaw/140479767649520/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51668 - "GET /gradio_api/stream/aovtw3pnsaw/140479660131472/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51667 - "GET /gradio_api/stream/aovtw3pnsaw/140479660131472/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51668 - "GET /gradio_api/stream/aovtw3pnsaw/140479767649520/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51667 - "GET /gradio_api/stream/aovtw3pnsaw/140479767649520/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51668 - "GET /gradio_api/stream/aovtw3pnsaw/140479660131472/15/playlist.m3u8 HTTP/1.1" 200 OK
INFO:     171.88.165.224:51668 - "GET /gradio_api/stream/aovtw3pnsaw/140479767649520/15/playlist.m3u8 HTTP/1.1" 200 OK`
在这里无限死循环

**Comment by ForgetThatNight** [comment]
也不知道从哪里跑出来的info信息 全局检索没有搜到

**Comment by Henry-23** [comment]
这个是gradio的video streaming的info，并不是死循环

**Comment by Henry-23** [comment]
app.py里修改一下，不要用uvicorn

**Comment by ForgetThatNight** [comment]
> app.py里修改一下，不要用uvicorn

感谢，已解决，TTS超时THG超时的异常也顺便消失了。。。

**Comment by xuxinli** [comment]
怎么解决的？

**Comment by ForgetThatNight** [comment]
> 怎么解决的？

删uvicorn相关代码，用demo.launch
