### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by luffy-git** [Henry-23/VideoChat#15]
![image](https://github.com/user-attachments/assets/e5e12617-5e58-4699-9061-8a22e98aad86)

**Comment by luffy-git** [comment]
> 可以看看这个[issue](https://github.com/RVC-Boss/GPT-SoVITS/issues/1628)

好的，已经解决了，然后我的GPU内存不够，我换了另一个分支（cascade_only）运行。 现在启动报错如下：
![image](https://github.com/user-attachments/assets/817da0fe-25a9-455b-bbe6-c27c8d9646ae)

**Comment by Henry-23** [comment]
这个是权重下载不完整，检查一下

**Comment by luffy-git** [comment]
> 这个是权重下载不完整，检查一下

权重指的是 weights 目录下的东西吗？

**Comment by Henry-23** [comment]
> > 这个是权重下载不完整，检查一下
> 
> 
> 
> 权重指的是 weights 目录下的东西吗？

请参考Readme里关于GPT-Sovits权重配置的说明

**Comment by luffy-git** [comment]
> > > 这个是权重下载不完整，检查一下
> > 
> > 
> > 权重指的是 weights 目录下的东西吗？
> 
> 请参考Readme里关于GPT-Sovits权重配置的说明

好的我看到了，但是似乎只有Windows整合包和MAC整合包，没有Linux下的整合包。
