### ISSUE TITLE
一直卡着开始生成

### ISSUE THREAD

**Issue by kplxwb** [Henry-23/VideoChat#17]
![image](https://github.com/user-attachments/assets/7c6a1040-9640-4943-a722-31f709f84dcf)
![image](https://github.com/user-attachments/assets/985ea7a5-2353-4f8a-8493-19cd7140a676)

**Comment by kplxwb** [comment]
![image](https://github.com/user-attachments/assets/6bcfc210-9c1f-472e-82ef-4c0084f13559)
这里有个str no choices解决不了

**Comment by ThinkThrice** [comment]
str no choices问题怎么解决的呢？
