### ISSUE TITLE
gradio视频流卡顿

### ISSUE THREAD

**Issue by MiChongGET** [Henry-23/VideoChat#2]
不知道作者有没有遇到视频流卡顿，丢字的现象，有时候会多段音频重叠，我这边几乎每次都会卡顿，但是后台合成的完整视频是好的，几乎每个字都有，我用的是4090的卡

**Comment by Henry-23** [comment]
这个应该是gradio的video streaming问题，我之前给他们提过[issue](https://github.com/gradio-app/gradio/issues/9251)，但是没有回应。

方便看下在用的gradio版本吗？我这边用的gradio 4.40测试版，公司环境还不支持gradio 5。可以试下最新的gradio，不知道现在有没有修复这个问题。

另外，有个[gradio-webrtc](https://github.com/freddyaboulton/gradio-webrtc)的项目，是负责gradio video streaming的开发者做的，但是目前还不支持音视频同步传输，可以关注一下，后续支持的话，可以替换掉现在的Video Stream组件。

**Comment by MiChongGET** [comment]
我用的版本还是挺新的，5.4.0的

**Comment by Henry-23** [comment]
后台会合成若干.ts格式的视频片段，可以看看这几个片段是否是正常的。完整视频是使用这些视频片段合成的。

我观察到的问题是，前一个视频片段快结束时，yield一个新的视频片段就会造成视频流的卡顿或重复播放的问题。

Gradio的Video Streaming目前是基于HLS协议的，性能上相比webrtc要差，所以希望[gradio-webrtc](https://github.com/freddyaboulton/gradio-webrtc)能尽快支持音视频同步，直接换掉hhh

视频流这方面我不是很懂哈，如果解决了这个问题，欢迎提PR

**Comment by MiChongGET** [comment]
感谢❤，我是刚接触数字人的萌新😁，你的这套平台很适合小白上手，估计后面就算二次开发，也得用到webrtc相关的，https://github.com/lipku/LiveTalking 这个大佬用的就是webrtc相关的，我也准备去研究研究他的

**Comment by Henry-23** [comment]
好的，感谢。这个项目我也有关注，主要是不太懂视频流，所以用的gradio video streaming，适合做在线demo。但是实际的效果确实不行，我看智谱GLM-4-Voice的web demo用的gradio audio streaming，效果也不好😂。所以只能许愿Gradio-webrtc能尽快支持了。
