### ISSUE TITLE
本地调用Qwen 可以不流式输出吗

### ISSUE THREAD

**Issue by Crescentz** [Henry-23/VideoChat#21]
本地调用Qwen 可以不流式输出吗
因为Qwen里的流失输出会报错  str没有choice

**Comment by Henry-23** [comment]
infer方法是非流式的

**Comment by Crescentz** [comment]
在 src/pipeline_llm.py 里 把            # LLM streaming out
            llm_response_txt, user_messages, llm_time_cost = self.llm.infer_stream(
                user_input_txt, 
                user_messages, 
                self.llm_queue, 
                chunk_size,
                chat_mode
            )
改成 Infer 就可以了吗，其他流式，LLM非流式

**Comment by Crescentz** [comment]
> infer方法是非流式的

感谢，我单独运行llm.py试了， infer_stream会报错 infer不会
但是整体怎么替换成infer这个又不太清楚

**Comment by Henry-23** [comment]
参考infer函数的输入输出改一下就可以，关键是拿到llm输出的文本并放到llm_queue中，这样tts才会开始处理
