### ISSUE TITLE
自定义声音要修改哪里？

### ISSUE THREAD

**Issue by aa007shuai** [Henry-23/VideoChat#8]
感谢作者提供这么好的工具，想问一下如果想使用自己上传声音生成数字人短视频的话，需要修改哪里？感谢作者！

**Comment by Henry-23** [comment]
请参考[这个说明](https://github.com/Henry-23/VideoChat/tree/master?tab=readme-ov-file#52-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E5%AD%97%E4%BA%BA%E9%9F%B3%E8%89%B2)

**Comment by aa007shuai** [comment]
我录了跟参考语音相同内容的音频，按照说明放进去，同时代码也改了，生成的视频中，音频中原来的声音也生成到视频里面了。

**Comment by Henry-23** [comment]
重试也还是这样吗？

**Comment by aa007shuai** [comment]
是的，音频里面的原本的声音也会生成进去

> 重试也还是这样吗？

**Comment by Henry-23** [comment]
我这边没有这样的问题诶，不太可能把参考音频的内容一起生成进去的，有些疑惑hhh

**Comment by Henry-23** [comment]
可以看看[在线demo](https://www.modelscope.cn/studios/AI-ModelScope/video_chat)的音色克隆功能

**Comment by aa007shuai** [comment]
我重新更新下代码，重新部署一下试试，感谢大佬。有问题再来

**Comment by aa007shuai** [comment]
大佬好，我重新更新代码，升级Torch重新部署，重新录了音，按照上面的说明修改了代码发现还是不行。原有的语音有时候在第一句，有时候在中间，有时候会有空白（生成的视频有一段没有声音），请问对录音文件的一些格式有要求吗？

**Comment by Henry-23** [comment]
> 大佬好，我重新更新代码，升级Torch重新部署，重新录了音，按照上面的说明修改了代码发现还是不行。原有的语音有时候在第一句，有时候在中间，有时候会有空白（生成的视频有一段没有声音），请问对录音文件的一些格式有要求吗？

你好，请问之前的问题（录音被合成进入视频）是否依然存在？ 
录音文件我是用wav格式的，3-10s的长度，吐字清晰即可。

**Comment by aa007shuai** [comment]
@Henry-23 感谢大佬解答，之前的问题依然存在，我看咱们代码里面是分段生成的视频，有时候第一段会变成空白（字数较少）或者直接替换成录音的原音。有的时候会在中间的某一段加入会被替换成录音原音。这个现象是随机的，我录的语音8秒，跟示例语音的内容完全一致，吐字也清晰，是通过iphone的语音备忘录录完后直接改的文件后缀wav。请问有可能是哪的原因？是不是可能是TTS.py的run方法或者是audio_postprocess方法有问题？

**Comment by Henry-23** [comment]
> @Henry-23 感谢大佬解答，之前的问题依然存在，我看咱们代码里面是分段生成的视频，有时候第一段会变成空白（字数较少）或者直接替换成录音的原音。有的时候会在中间的某一段加入会被替换成录音原音。这个现象是随机的，我录的语音8秒，跟示例语音的内容完全一致，吐字也清晰，是通过iphone的语音备忘录录完后直接改的文件后缀wav。请问有可能是哪的原因？是不是可能是TTS.py的run方法或者是audio_postprocess方法有问题？

可以去GPT-Sovits的issue里看一下，这部分代码我只做了面向对象的重构，核心的推理没有较大的改变，我自己在项目开发过程中没有碰到过这样的问题。
你可以试试右下角的语音克隆，在gradio里录制语音，然后输入你的问题内容，看看生成的结果还存不存在这样的问题。

**Comment by aa007shuai** [comment]
好的  感谢大佬  我再试试

**Comment by ThinkThrice** [comment]
我也遇到了同样的问题，请问前辈解决了吗？

> [@Henry-23](https://github.com/Henry-23) 感谢大佬解答，之前的问题依然存在，我看咱们代码里面是分段生成的视频，有时候第一段会变成空白（字数较少）或者直接替换成录音的原音。有的时候会在中间的某一段加入会被替换成录音原音。这个现象是随机的，我录的语音8秒，跟示例语音的内容完全一致，吐字也清晰，是通过iphone的语音备忘录录完后直接改的文件后缀wav。请问有可能是哪的原因？是不是可能是TTS.py的run方法或者是audio_postprocess方法有问题？
